@extends('errors.layout-errors')
@section('title', '500')
@section('code', '500')
@section('title_page', 'Error interno de servidor')
@section('message', 'Ya estamos trabajando para solucionar este problema.')
